apiVersion: v1
kind: Pod
# apiVersion: apps/v1
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-client
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: 521Mi
          cpu: '1'
        requests:
          memory: 256Mi
          cpu: '0.2'
