apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
  # namespace: complex-app
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
