sudo: required
services:
  - docker
before_install:
  - openssl <travis-encryption> -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # download google sdk | install it instance provided by travis ci
  - source $HOME/google-cloud-sdk/path.bash.inc
  #looks at default install directory of sdk and source it at path.bash.inc
  # sets up google cloud locally on your machine for you
  - gcloud components update kubectl
  # install and update kubectl inside travis environment
  - gcloud auth activate-service-acount --key-file service-account.json
  # tells google cloud who we are and set credentials inside a file called service-account.json
  - gcloud config set project multi-k8s-396215
  #which project to use to run
  - gcloud config set compute/zone me-central1-a
  # setting the compute zone
  - gcloud container clusters get-credentials k8scluster
  # sets which k8 cluster to use in gcp

  # Docker  Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Build Images
  - docker build -t bixoloo/react-test -f ./client/Dockerfile.dev ./client
  # the file should come from client dir which has your project with Dockerfile.dev ./client is build context

script:
  - docker run bixoloo/react-test npm run test -- --coverage
