apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: dev
spec:
  rules:
    - host: myapp.com
      # must be a valid ip address
      http:
        paths:
          - backend:
              serviceName: myapp-internal-service
              servicePort: 9000
