apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: complex-app
  annotations:
    kubernetes.io/ingress.class: nginx
    # ingress controller based on nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    #  rewrites on request and remove the /api in the incoming request

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port:
                  number: 5000
