apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
  namespace: complex-app
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
