apiVersion: v1
kind: Pod
# apiVersion: apps/v1
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      #image: bixoloo/multi-client
      image: bixoloo/multi-worker
      ports:
        - containerPort: 3000
